SYSTEM_ADMIN = "ADMIN"
CAFE_OWNER = "OWNER"
CAFE_MANAGER = "MANAGER"
CAFE_STAFF = "STAFF"

ACCESS_LEVELS = [SYSTEM_ADMIN, CAFE_OWNER, CAFE_MANAGER, CAFE_STAFF]

CHEF = "CHEF"
WAITER = "WAITER"
CASHIER = "CASHIER"

PENDING = "PENDING"
APPROVED = "APPROVED"
REJECTED = "REJECTED"
